export enum AGENT_TYPE{
    MGA_PRINCIPAL = "MGA_PRINCIPAL",
    MGA_ADMIN = "MGA_ADMIN",
    AGENCY_PRINCIPAL = "AGENCY_PRINCIPAL",
    AGENCY_ADMIN = "AGENCY_ADMIN",
    GENERAL_AGENT = "GENERAL_AGENT"
}